### ISSUE TITLE
k1k0 errors with second parameter 1 and Val(1)

### ISSUE THREAD

**Issue by miguelraz** [jverzani/SpecialPolynomials.jl#13] opened 2020-11-21 19:40 UTC
Whilst trying to recreate the code [here](https://htmlpreview.github.io/?https://github.com/rurz/WG_FractionalEvolution/blob/main/tests/Jacobi.jl.html), I ran into this issue:

```julia
using SpecialPolynomials
J = Jacobi{0, -2, Int64, 11}
SpecialPolynomials.k1k0(J,1)
ERROR: MethodError: no method matching k1k0(::Type{Jacobi{0,-2,Int64, 11}}: ::Val{1})
...

SpecialPolynomials.k1k0(J, Val(1))
ERROR: MethodError: no method matching k1k0(::Type{Jacobi{0,-2,Int64, 11}}: ::Val{1})
...
versioninfo()
Julia Version 1.6.0-DEV.1442
SpecialPolynomials v0.1.0
```

**Comment by miguelraz** [comment] 2020-11-21 19:51
The problem is that by the time we get to this line https://github.com/jverzani/SpecialPolynomials.jl/blob/3dad860da0506b441460992cee6a120cb7b6c4d5/src/Orthogonal/Jacobi.jl#L43

n == 1, y == 0 => (y - n + 1) == 0
=> iszero(den) == true
and then the recursion fails.

**Comment by jverzani** [comment] 2020-11-21 21:48
Thanks for this report. The issue is the use of the ratio of leading terms in the framework used here. When n=1, \alpha=0 and \beta=-2 we get the leading term of J1 is 0 and then the setup goes awry. I think I would need to special case this just as you did. In general, I wouldn't expect this package to compete performance wise with HyperGeometricFunctions.jl but it shouldn't be too bad for reasonable size n.

**Comment by miguelraz** [comment] 2020-11-21 23:58
Thanks for chiming in on a Saturday.
This isn't a blocking issues, it is a prototyped code, but @rurz will probably want to know why it was erroring his code.

**Comment by jverzani** [comment] 2020-11-22 16:31
If I have this right, the Jacobi polynomials are only orthogonal polynomials when alpha and beta > -1, as otherwise the weight function x^alpha * (1-x)^beta is not integrable. The formula from `HyperGeometricFunctions` imposes that condition, in `SpecialPolynomials` the Clenshaw algorithm for evaluation fails in the case you discovered (and others, as it will when either of these is 0: n+1+alpha+beta or 2n+alpha+beta). The formula in that pluto notebook gives an alternate formulation in those cases. It would be nice if there were a fast means to compute it. As is, I could make a special method for that evaluation. It is a special case, but might be of interest for others.

**Comment by jverzani** [comment] 2020-11-22 21:10
Once #14 is merged, the notebook could evaluate Jacobi Polynomials through any of these three ways, where `J = Jacobi{alpha, beta}`

```
SpecialPolynomials.classical_hypergeometric(J,n,x) # Will use HyperGeometricFunctions `pFq` function
basis(J,n)(x)  # uses Clenshaw evalution
SpecialPolynomials.jacobi_eval(alpha, beta, n, x)      # use series formula from the notebook
```

I would expect the first to be the most performant, the second to be competitive for smaller n and the latter to be really slow.

**Comment by rurz** [comment] 2020-11-23 17:10
¡Amazing! Thank you for taking the report on the evaluation of the `Jacobi`. It is right, I think this is a very particular case when the conditions alpha, beta > -1 is not achieved, nevertheless, as the theory predicts, the functions need to be evaluated and return a reasonable value.

**Comment by jverzani** [comment] 2020-11-23 18:27
Well, hopefully I computed the right value, but the method used for that case is pretty slow to compute. Thanks for bringing this to my attention.

**Closed as completed** 2020-11-23 20:21 UTC
